/**
 * turns table — Phase 2 schema stub.
 *
 * NOT used in the MVP; all runtime state lives in Express sessions (memorystore).
 * Defined now so migrations can be generated and reviewed before Task #6 wires
 * persistence.
 *
 * Each row stores one conversation turn (employee OR manager) from a practice
 * session.  A full session has at most 10 turns (5 employee + 5 manager).
 */
import {
  pgTable,
  serial,
  text,
  integer,
  timestamp,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { sessionsTable } from "./sessions.js";

export const turnsTable = pgTable("turns", {
  /** Auto-incrementing surrogate key. */
  id: serial("id").primaryKey(),

  /** The Express session ID this turn belongs to. */
  session_id: text("session_id")
    .notNull()
    .references(() => sessionsTable.id, { onDelete: "cascade" }),

  /**
   * 1-indexed position of this turn within the session (1–5 per role).
   * Combined with `role` it uniquely identifies a turn within a session.
   */
  turn_index: integer("turn_index").notNull(),

  /**
   * "employee" — the AI persona's spoken line (generated by ElevenLabs agent).
   * "manager"  — the human manager's spoken line (transcribed by Whisper).
   */
  role: text("role").notNull(),

  /** Whisper transcript for manager turns; ElevenLabs transcript for employee turns. */
  transcript: text("transcript").notNull(),

  /**
   * GPT-4o-mini coaching tip for this manager turn (strength + improvement).
   * Null for employee turns.
   */
  coaching_tip: text("coaching_tip"),

  /**
   * Simulated employee emotional intensity (1 = calm, 10 = highly distressed/angry).
   * Null for manager turns.
   */
  emotion_score: integer("emotion_score"),

  /** When this turn was recorded. */
  created_at: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

/**
 * Zod schema for inserting a new turn row.
 * Extends the auto-generated schema with explicit role validation.
 */
export const insertTurnSchema = createInsertSchema(turnsTable).extend({
  role: z.enum(["employee", "manager"]),
  turn_index: z.number().int().min(1).max(5),
  emotion_score: z.number().int().min(1).max(10).optional(),
});

export type InsertTurn = typeof insertTurnSchema.type;
export type Turn = typeof turnsTable.$inferSelect;
